# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    inputs:
      bypass:
        type: choice
        description: Bypass Unittests
        required: true
        default: 'No'
        options: 
        - No
        - Yes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Run unittests
        id: unittests
        run: |
          ls -la # some arbitrary command that will not fail, to mimic running tests successfully
          echo "Exit code: $?"
      
      - name: Set check status
        id: set_status
        run: |
          if [ "${{ github.event.inputs.bypass }}" == "No" ]; then
            echo "Check passed"
            echo "::set-output name=status::success"
          else
            echo "Check bypassed"
            echo "::set-output name=status::skipped"
          fi

      - name: Create status check
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const status = '${{ steps.set_status.outputs.status }}';
            await github.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha,
              state: status === 'success' ? 'success' : 'failure',
              context: 'unittest'
            });