# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
    inputs:
      bypass:
        type: choice
        description: Bypass Unittests
        required: true
        default: 'No'
        options: 
        - No
        - Yes
         

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      statuses: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Run unittests
        id: unittests
        run: |
          ls -la # some arbitrary command that will not fail, to mimic running tests successfully
          echo "Exit code: $?"
      
      - name: Set check status
        id: set_status
        run: |
          if [ "${{ github.event.inputs.bypass }}" == "Yes" ]; then
            echo "Bypass is set to Yes"
            echo "status=success" >> $GITHUB_OUTPUT
          else
            if [ "${{ steps.unittests.outcome }}" == "success" ]; then
              echo "Tests passed"
            echo "status=success" >> $GITHUB_OUTPUT
            else
              echo "Tests failed"
            echo "status=failed" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Create status check
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -f "state=${{ steps.set_status.outputs.status }}" \
            -f "target_url=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \      
            -f description='The build succeeded!' \
            -f context=unittest

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}